name: "linting"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  shared:
    name: linting
    uses: cloudnationhq/az-cn-shared-tf-workflows/.github/workflows/linting.yml@main
